spring:
  application:
    name: WorkSphere

  datasource:
    url: jdbc:mysql://localhost:3306/worksphere_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

cloudinary:
  cloud-name: dylbcapwn
  api-key: 579356261936345
  api-secret: kKqKDa8V72ftWM3T7086Mj6k_Y8
